name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        uvicorn main:app --reload &
        sleep 5  # Give server time to start
        curl -X POST "http://localhost:8000/functions" -H "Content-Type: application/json" -d '{"name":"test","route":"/test","language":"python","timeout":5,"code":"print('\''Hello!'\''')"}'
    - name: Build and test Docker
      run: |
        docker build -t serverless-platform .
        docker run -d -p 8000:8000 serverless-platform
        sleep 5
        curl -X POST "http://localhost:8000/functions/1/execute"
